<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <info@vitexsoftware.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease;

use Ease\Anonym;
use PHPUnit\Framework\Attributes\CoversClass;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:38.
 */
#[CoversClass(Anonym::class)]
class AnonymTest extends BrickTest
{
    protected Anonym $anonym;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->anonym = new Anonym();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\Anonym::setObjectName
     */
    public function testSetObjectName(): void
    {
        $this->assertEquals('Test', $this->anonym->setObjectName('Test'));
        $_SERVER['REMOTE_ADDR'] = '127.0.0.1';
        $this->assertEquals(
            'Ease\Anonym@127.0.0.1',
            $this->anonym->setObjectName(),
        );
        $_SERVER['REMOTE_USER'] = 'tester';
        $this->assertEquals(
            'Ease\Anonym@127.0.0.1 [tester]',
            $this->anonym->setObjectName(),
        );
    }

    /**
     * @covers \Ease\Anonym::remoteToIdentity
     */
    public function testRemoteToIdentity(): void
    {
        $_SERVER['REMOTE_USER'] = null;
        $_SERVER['REMOTE_ADDR'] = '127.0.0.1';
        $this->assertEquals('127.0.0.1', $this->anonym->remoteToIdentity());
        $_SERVER['REMOTE_USER'] = 'tester';
        $this->assertEquals(
            '127.0.0.1 [tester]',
            $this->anonym->remoteToIdentity(),
        );
    }

    /**
     * @covers \Ease\Anonym::getUserLevel
     */
    public function testGetUserLevel(): void
    {
        $this->assertEquals(-1, $this->anonym->getUserLevel());
    }

    /**
     * @covers \Ease\Anonym::getUserID
     */
    public function testGetUserID(): void
    {
        $this->assertNull($this->anonym->getUserID());
    }

    /**
     * @covers \Ease\Anonym::getUserLogin
     */
    public function testGetUserLogin(): void
    {
        $this->assertNull($this->anonym->getUserLogin());
    }

    /**
     * @covers \Ease\Anonym::isLogged
     */
    public function testIsLogged(): void
    {
        $this->assertFalse($this->anonym->isLogged());
    }

    /**
     * @covers \Ease\Anonym::getSettingValue
     */
    public function testGetSettingValue(): void
    {
        $this->assertNull($this->anonym->getSettingValue('test'));
    }

    /**
     * @covers \Ease\Anonym::setSettingValue
     */
    public function testSetSettingValue(): void
    {
        $this->anonym->setSettingValue('test', true);
        $this->assertEquals(['test' => true], $this->anonym->settings);
    }

    /**
     * @covers \Ease\Anonym::getUserEmail
     */
    public function testGetUserEmail(): void
    {
        $this->assertEmpty($this->anonym->getUserEmail());
    }

    /**
     * @covers \Ease\Anonym::getPermission
     */
    public function testGetPermission(): void
    {
        $this->assertNull($this->anonym->getPermission());
    }

    /**
     * @covers \Ease\Anonym::logout
     */
    public function testLogout(): void
    {
        $this->assertTrue($this->anonym->logout());
    }
}
