<?php

/**
 * Basic system atom.
 *
 * @author     Vitex <info@vitexsoftware.cz>
 * @copyright  2009-2021 info@vitexsoftware.cz (G)
 */
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <info@vitexsoftware.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease;

use Ease\Atom;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\CoversMethod;

/**
 * Test class for EaseAtom.
 * Generated by PHPUnit on 2012-03-17 at 23:53:07.
 *
 * @author     Vitex <info@vitexsoftware.cz>
 * @copyright  2009-2023 info@vitexsoftware.cz (G)
 */
#[CoversClass(Atom::class)]
#[CoversMethod(Atom::class, 'getObjectName')]
#[CoversMethod(Atom::class, '__toString')]
#[CoversMethod(Atom::class, 'draw')]
class AtomTest extends \PHPUnit\Framework\TestCase
{
    protected ?Atom $atom = null;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->atom = new Atom();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Ease\Atom::getObjectName
     */
    public function testgetObjectName(): void
    {
        $this->assertNotEmpty($this->atom->getObjectName());
    }

    /**
     * @covers \Ease\Atom::__toString
     */
    public function testToString(): void
    {
        $this->assertEmpty($this->atom->__toString());
    }

    /**
     * @covers \Ease\Atom::draw
     *
     * @param null|mixed $whatWant
     */
    public function testDraw($whatWant = null): void
    {
        $this->assertEquals('', $this->atom->draw());
    }
}

// @codeCoverageIgnoreEnd
