<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <info@vitexsoftware.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease;

use Ease\Sand;
use PHPUnit\Framework\Attributes\CoversClass;

/**
 * @codingStandardsIgnoreFile
 *
 * @codeCoverageIgnoreStart
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 09:50:39.
 */
#[CoversClass(Sand::class)]
class SandTest extends AtomTest {

    protected ?Sand $sand = null;

    protected function setUp(): void {
        $this->sand = new \Ease\Sand();
    }

    /**
     * @covers \Ease\Sand::dataReset
     */
    public function testDataReset(): void {
        $this->sand->dataReset();
        $this->assertEmpty($this->sand->getData());
    }

    /**
     * @covers \Ease\Sand::setData
     */
    public function testSetData(): void {
        $data = ['a' => 1, 'b' => 2];
        $this->sand->setData($data, true);
        $this->assertEquals($data, $this->sand->getData());
    }

    /**
     * @covers \Ease\Sand::getData
     *
     * @depends testSetData
     */
    public function testGetData(): void {
        $data = ['a' => 1, 'b' => 2];
        $this->sand->setData($data);
        $this->assertEquals($data, $this->sand->getData());
    }

    /**
     * @covers \Ease\Sand::getDataCount
     */
    public function testGetDataCount(): void {
        $this->sand->dataReset();
        $data = ['a' => 1, 'b' => 2];
        $this->sand->setData($data);
        $this->assertEquals(2, $this->sand->getDataCount());
    }

    /**
     * @covers \Ease\Sand::getDataValue
     */
    public function testGetDataValue(): void {
        $data = ['a' => 1, 'b' => 2];
        $this->sand->setData($data);
        $this->assertEquals(2, $this->sand->getDataValue('b'));
        $this->assertNull($this->sand->getDataValue('c'));
    }

    /**
     * @covers \Ease\Sand::setDataValue
     */
    public function testSetDataValue(): void {
        $this->setUp();
        $this->sand->setDataValue('c', 3);
        $this->assertEquals(3, $this->sand->getDataValue('c'));
    }

    /**
     * @covers \Ease\Sand::unsetDataValue
     */
    public function testUnsetDataValue(): void {
        $this->setUp();
        $data = ['a' => 1, 'b' => 2];
        $this->sand->setData($data);
        $this->assertTrue($this->sand->unsetDataValue('a'));
        $this->assertNull($this->sand->getDataValue('a'));
        $this->assertFalse($this->sand->unsetDataValue('c'));
    }

    /**
     * @covers \Ease\Sand::takeData
     */
    public function testTakeData(): void {
        $this->setUp();
        $data = ['d' => 4, 'e' => 5];
        $this->sand->takeData($data);
        $this->assertEquals(5, $this->sand->getDataValue('e'));
        $data = ['f' => 6, 'g' => 7];
        $this->sand->takeData($data);
        $this->assertEquals(4, $this->sand->getDataValue('d'));
    }

    /**
     * @covers \Ease\Sand::draw
     *
     * @param null|mixed $whatWant
     */
    public function testDraw($whatWant = null): void {
        $this->setUp();
        $this->assertEmpty($this->sand->draw());
    }
}

// @codeCoverageIgnoreEnd
