<?php

namespace Test\Ease\Logger;

use Ease\Logger\ToConsole;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-05 at 05:48:05.
 */
class ToConsoleTest extends ToMemoryTest
{
    /**
     * @var ToConsole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() : void
    {
        $this->object = new ToConsole;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() : void
    {
        
    }

    /**
     * @covers Ease\Logger\ToConsole::set
     * @todo   Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToConsole::addToLog
     * @covers Ease\Logger\Loggingable::addToLog
     */
    public function testAddToLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToConsole::getTypeColor
     * @todo   Implement testGetTypeColor().
     */
    public function testGetTypeColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Ease\Logger\ToConsole::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
