<?php

namespace Test\Ease\Logger;

use Ease\Logger\ToEmail;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-08-29 at 21:06:19.
 */
class ToEmailTest extends ToMemoryTest
{
    /**
     * @var ToEmail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ToEmail('info@vitexsoftware', 'ToEmailLOgger  test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test Constructor
     *
     * @covers Ease\Logger\ToEmail::__construct
     */
    public function testConstructor()
    {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMockForAbstractClass();

        $mock->__construct('info@vitexsoftware.cz', 'test');
        $this->assertInstanceOf('\Ease\Mailer', $mock->mailer);
    }

    /**
     * @covers Ease\Logger\ToEmail::singleton
     */
    public function testSingleton()
    {
        $this->assertInstanceOf('Ease\Logger\ToEmail', ToEmail::singleton());
    }

    /**
     * @covers Ease\Logger\ToEmail::addToLog
     */
    public function testAddToLog()
    {
        $this->assertEquals(4, $this->object->addToLog($this, 'test'));
    }

    /**
     * @covers Ease\Logger\ToEmail::__destruct
     */
    public function test__destruct()
    {
        $this->assertEquals('', $this->object->__destruct());
    }
}
