<?php

namespace Test\Ease\Logger;

use Ease\Logger\ToSyslog;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:58:23.
 */
class ToEventlogTest extends ToSyslogTest
{
    /**
     * @var Ease\Logger\ToSyslog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new \Ease\Logger\ToEventlog();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }
    
    /**
     * @covers \Ease\Logger\ToEventlog::finalizeMessage
     */
    public function testFinalizeMessage()
    {
        $this->assertEquals('zlutoucky kun', $this->object->finalizeMessage('žluťoučký kůň'));
        
    }
    
    
}
