<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <info@vitexsoftware.cz>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Ease\Logger;

use Ease\Logger\ToFile;
use PHPUnit\Framework\Attributes\CoversClass;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-17 at 23:59:52.
 */
#[CoversClass(ToFile::class)]
class ToFileTest extends ToMemoryTest
{
    protected Logger $tofile;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->tofile = new ToFile(sys_get_temp_dir().'/');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test Constructor.
     *
     * @covers \Ease\Logger\ToFile::__construct
     */
    public function testConstructor(): void
    {
        $classname = \get_class($this->tofile);

        $mock = $this->getMockBuilder($classname)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();

        $mock->__construct(sys_get_temp_dir().'/');
        $this->assertEquals(sys_get_temp_dir().'/Ease.log', $mock->logFileName);
    }

    /**
     * @covers \Ease\Logger\ToFile::singleton
     */
    public function testSingleton(): void
    {
        $this->assertInstanceOf('Ease\Logger\ToFile', ToFile::singleton());
    }

    /**
     * @covers \Ease\Logger\ToFile::setupLogFiles
     */
    public function testSetupLogFiles(): void
    {
        $this->expectException('\Exception');
        $this->assertEquals(sys_get_temp_dir().'/Ease.log', $this->tofile->logFileName);
        $this->tofile->setupLogFiles('/var/log');
    }

    /**
     * @covers \Ease\Logger\ToFile::addToLog
     */
    public function testAddToLog(): void
    {
        $this->assertIsInt($this->tofile->addToLog($this, 'test'));
    }

    /**
     * @covers \Ease\Logger\ToFile::testDirectory
     */
    public function testTestDirectory(): void
    {
        $this->assertTrue($this->tofile->testDirectory(sys_get_temp_dir()));
        $this->expectException('\Exception');
        \Ease\Logger\ToFile::testDirectory('none', true);
        $this->expectException('\Exception');
        \Ease\Logger\ToFile::testDirectory('/root', true, true);
        $this->expectException('\Exception');
        \Ease\Logger\ToFile::testDirectory('/root', true, true, true);
    }

    /**
     * @covers \Ease\Logger\ToFile::__destruct
     */
    public function testDestruct(): void
    {
        $this->assertEmpty($this->tofile->__destruct());
    }
}
