name: PHPUnit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      env: 
        DEBIAN_FRONTEND: "noninteractive"
        LC_ALL: "en_US.UTF-8"
        LANG: "en_US.UTF-8"
    - name: Prepare Environment
      run: |
        sudo apt-get install -y composer exim4
        composer update
    - name: Run tests
      run: make phpunit
